### ISSUE TITLE
[Feature Request] Add support for fleet carriers

### ISSUE THREAD

**Issue by BraINstinct0** [alterNERDtive/EDMC-FuelStatus#1]
Suggestion: Though the mechanism might be quite different, I believe the main idea might be the same; so instead of ignoring fleet carriers, give an option to display FC fuel(tritium) level when docked to one which you own.

**Comment by alterNERDtive** [comment]
Fleet carrier fuel levels are an entirely different thing. I’m pulling fuel levels from the `status.json` file.

AFAI can see from the journal docs, the _only_ occasions where you can get the _carrier_ fuel levels are if you open carrier _management_ (not when you dock, not when you open station services) for your own carrier, or when you deposit fuel.

In both cases I honestly don’t see a use for displaying what you can already see on the screen ingame anyway.

**Comment by BraINstinct0** [comment]
Seems like a very reasonable analysis, so closing this issue! Thanks for all the code :)
