### ISSUE TITLE
[Feature Request] Remaining Jumps In Route

### ISSUE THREAD

**Issue by HalJordan** [alterNERDtive/EDMC-FuelStatus#3]
The journal includes an event when you jump, updating the RemainingJumpsInRoute:

`{ "timestamp":"2022-01-04T07:40:44Z", "event":"FSDTarget", "Name":"Outotz ND-J d9-1", "SystemAddress":44954618067, "StarClass":"F", "RemainingJumpsInRoute":6 }`

Can this info be added to your output?

It's just as simple as the rest of the plugin, and is relative when checking to see if you should top up, or if you're almost at your destination. Since you have to go to the external panel to see this, they can't have it on the hud anywere.

**Comment by alterNERDtive** [comment]
Hey! This is kind of out of scope for a plugin that displays fuel levels. Should be trivial to implement yourself though if you know a little bit of programming and look at the code for this one + https://github.com/EDCD/EDMarketConnector/blob/main/PLUGINS.md#journal-entry.
